#include-once

;~ Global $ihandle

Global Enum $EDT_NULL, $EDT_SOFTWARE, $EDT_BURNINGSVIDEO, $EDT_DIRECT3D8, $EDT_DIRECT3D9, $EDT_OPENGL, $EDT_COUNT

Global Enum _;E_MATERIAL_FLAG
$EMF_WIREFRAME = 0x1, _
$EMF_POINTCLOUD = 0x2, _
$EMF_GOURAUD_SHADING = 0x4, _
$EMF_LIGHTING = 0x8, _
$EMF_ZBUFFER = 0x10, _
$EMF_ZWRITE_ENABLE = 0x20, _
$EMF_BACK_FACE_CULLING = 0x40, _
$EMF_FRONT_FACE_CULLING = 0x80, _
$EMF_BILINEAR_FILTER = 0x100, _
$EMF_TRILINEAR_FILTER = 0x200, _
$EMF_ANISOTROPIC_FILTER = 0x400, _
$EMF_FOG_ENABLE = 0x800, _
$EMF_NORMALIZE_NORMALS = 0x1000, _
$EMF_TEXTURE_WRAP = 0x2000, _
$EMF_ANTI_ALIASING = 0x4000, _
$EMF_COLOR_MASK = 0x8000, _
$EMF_COLOR_MATERIAL = 0x10000

Global Enum _;EMD2_ANIMATION_TYPE
$EMAT_STAND, _
$EMAT_RUN, _
$EMAT_ATTACK, _
$EMAT_PAIN_A, _
$EMAT_PAIN_B, _
$EMAT_PAIN_C, _
$EMAT_JUMP, _
$EMAT_FLIP, _
$EMAT_SALUTE, _
$EMAT_FALLBACK, _
$EMAT_WAVE, _
$EMAT_POINT, _
$EMAT_CROUCH_STAND, _
$EMAT_CROUCH_WALK, _
$EMAT_CROUCH_ATTACK, _
$EMAT_CROUCH_PAIN, _
$EMAT_CROUCH_DEATH, _
$EMAT_DEATH_FALLBACK, _
$EMAT_DEATH_FALLFORWARD, _
$EMAT_DEATH_FALLBACKSLOW, _
$EMAT_BOOM, _
$EMAT_COUNT
